version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:1
    restart: unless-stopped
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    image: service:1
    restart: unless-stopped
    volumes:
      - ./service:/usr/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:1
    restart: unless-stopped
    volumes:
      - ./frontend/src:/usr/app/src
  proxy:
    image: nginx:1.19.2-alpine
    restart: unless-stopped
    depends_on:
      - service
      - backend
      - frontend
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf